data:
  data_path: data/data.csv
  start_time: 2018-01-02
  end_time: 2025-04-24
  fit_start_time: 2018-01-02
  fit_end_time: 2023-01-01
  train: [2018-01-02, 2023-01-03]
  valid: [2023-01-04, 2023-12-29]
  test: [2024-01-02, 2025-04-24]

model:
  model_name: catboost
  kwargs:
    loss: RMSE
    learning_rate: 0.0421
    subsample: 0.8789
    max_depth: 6
    num_leaves: 100
    thread_count: 20
    grow_policy: Lossguide
    bootstrap_type: Poisson

output_dir: ml_model/output/catboost
checkpoints_output_dir: ml_model/checkpoints/catboost
horizon: 5       # 预测天数（可通过命令行 override，如 horizon=3）
lookback: 30     # 使用过去多少天作为输入窗口（可通过命令行 override）