
model:
  model_name: lightgbm
  kwargs:
    objective: regression
    colsample_bytree: 0.7
    subsample: 0.7
    learning_rate: 0.05
    n_estimators: 800
    num_leaves: 127
    max_depth: 6
    min_child_samples: 20
    min_gain_to_split: 0.0
    lambda_l1: 0.0
    lambda_l2: 0.0
    num_threads: 20
    dataset:
      data_path: data/data.csv
      start_time: 2018-01-02  # 数据开始时间
      end_time: 2025-04-24    # 数据结束时间
      fit_start_time: 2018-01-02  # 特征拟合开始时间(保证和训练集相同)
      fit_end_time: 2023-01-01
      train : [2018-01-02, 2023-01-03]    # 训练集时间范围
      valid : [2023-01-04, 2023-12-29]    # 验证集时间范围
      test : [2024-01-02, 2025-04-24]    # 测试集时间范围

output_dir: ml_model/output/lightgbm
checkpoints_output_dir: ml_model/checkpoints/lightgbm
horizon: 5       # 预测天数（可通过命令行 override，如 horizon=3）
lookback: 30     # 使用过去多少天作为输入窗口（可通过命令行 override）